#include "canvas/Persistency/Common/Wrapper.h"

#include "larcoreobj/GeoAlgo/GeoAABox.h"
#include "larcoreobj/GeoAlgo/GeoAlgoConstants.h"
#include "larcoreobj/GeoAlgo/GeoAlgoException.h"
#include "larcoreobj/GeoAlgo/GeoAlgo.h"
#include "larcoreobj/GeoAlgo/GeoAlgo-TypeDef.h"
#include "larcoreobj/GeoAlgo/GeoCone.h"
#include "larcoreobj/GeoAlgo/GeoCylinder.h"
#include "larcoreobj/GeoAlgo/GeoDirectedLine.h"
#include "larcoreobj/GeoAlgo/GeoHalfLine.h"
#include "larcoreobj/GeoAlgo/GeoLine.h"
#include "larcoreobj/GeoAlgo/GeoLineSegment.h"
#include "larcoreobj/GeoAlgo/GeoObjCollection.h"
#include "larcoreobj/GeoAlgo/GeoSphere.h"
#include "larcoreobj/GeoAlgo/GeoTrajectory.h"
#include "larcoreobj/GeoAlgo/GeoVector.h"
